local Config = {
     Inventory = {
          Gloves = {
               EquippedGlove = "Slap Glove Normal",
               EquippedFolder = "Normal",
               "Slap Glove Normal",
               -- "Slap Glove Blue"
               -- ...
          },

          MonkeyColors = {
               EquippedColor = "StarterCharacter",
               EquippedFolder = "Normal",
               "StarterCharacter"
               -- "StarterCharacterRed"
               -- ...
          },

          Itens = {
               -- Idk
          },
     },

     Coins = 0,
     XP = 0,
     Bananas = 0,
}

return Config